name: ✏️ Modify existing term
description: Suggest a change or correction to an existing term in EnvThes.
labels: ["type: modification", "status: needs review"]
assignees:
  - oggioniale
  - mabablue
body:
  - type: markdown
    attributes:
      value: |
        ✏️ Please describe your proposed modification below.
        ---
        👥 **Maintainers reviewing modifications:**
        - [@OggioniAle](https://github.com/OggioniAle)
        - [@mabablue](https://github.com/mabablue)
  - type: input
    id: term
    attributes:
      label: Proposed term (prefLabel)
      placeholder: e.g. "Groundwater level"
  - type: textarea
    id: definition
    attributes:
      label: Definition (English)
      description: Provide a clear and concise definition of the new term.
  - type: input
    id: broader
    attributes:
      label: Broader concept (if applicable)
  - type: textarea
    id: reference
    attributes:
      label: Source or reference (optional)
  - type: textarea
    id: reason
    attributes:
      label: Reason for inclusion
      description: Explain why this term should be added to the vocabulary.
  - type: input
    id: contributor
    attributes:
      label: Contributor ORCID (optional)
  - type: input
    id: affiliation
    attributes:
      label: Affiliation or project (optional)
