name: "Get secrets"
on:
  workflow_dispatch:
jobs:
  getsecrets:
    name: getsecrets
    runs-on: ubuntu-latest
    steps:
      - name: get
        shell: bash -l {0}
        env:
          CLIENT: ${{secrets.CLIENT}}
          STORAGE: ${{secrets.STORAGE}}
          FILE_NAME: ${{secrets.FILE_NAME}}
          SHEET_ID: ${{secrets.SHEET_ID}}
          PGP_KEY: ${{vars.WILBOL_PGP}}
        run: |
          echo $CLIENT > client.txt
          echo $STORAGE > storage.txt
          echo $FILE_NAME > file_name.txt
          echo $SHEET_ID > sheet_id.txt
          echo "$PGP_KEY" | gpg --import -
          gpg --trust-model always --encrypt-files --armor --recipient wilbol@ceh.ac.uk client.txt.asc storage.txt.asc file_name.txt.asc sheet_id.txt.asc

      - uses: actions/upload-artifact@v3
        with:
          name: testname-encrypted
          path: |
            client.txt.asc
            storage.txt.asc
            file_name.txt.asc
            sheet_id.txt.asc

      - name: cleanup
        shell: bash -l {0}
        run: |
          rm -rfv *
