name: "WillOnGit test workflow"
on:
  workflow_dispatch:
jobs:
  testjob:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: main
        shell: bash -l {0}
        env:
          PGP_KEY: ${{vars.WILBOL_PGP}}
        run: |
          echo "testing testing testing" >> testfile
          gpg --no-tty --trust-model always
          echo "$PGP_KEY" | gpg --no-tty --import -
          gpg --no-tty --encrypt --armor --recipient wilbol@ceh.ac.uk testfile

      - uses: actions/upload-artifact@v3
        with:
          name: testname-encrypted
          path: |
            testfile
            testfile.asc

      - name: cleanup
        shell: bash -l {0}
        run: |
          rm -f testfile testfile.asc
